name: SpawnTeleport
version: '${project.version}'
main: net.daechler.spawnteleport.SpawnTeleport
api-version: '1.20'
authors: [Daechler]
description: Teleport to the server spawn.
commands:
  spawn:
    description: Teleport to the server spawn.
    aliases: sp
    usage: /spawn
    permission: spawnteleport.use